services:
  hub-ideas:
    build:
      context: .
      args:
        - NEXT_PUBLIC_STAGING_ADMIN_EMAIL
        - NEXT_PUBLIC_STAGING_ADMIN_PASSWORD
        - NEXT_PUBLIC_ALLOW_CREDENTIALS
    container_name: hub-ideas
    ports:
      - "3001:3000"
    volumes:
      - ./prisma/data:/app/prisma/data
    env_file: .env
    environment:
      - DATABASE_URL=file:/app/prisma/data/hubideas.db
      - AUTH_TRUST_HOST=true
    restart: always
